### ISSUE TITLE
Suggestions for enhancement

### ISSUE THREAD

**Issue by Mtrade** [kaiusl/KLPlugins.DynLeaderboards#14]
Hi,
I was thinking about additional properties that might be accessible from the plugin, not sure if the below data would be accessible from ACC and can be implemented?

1) Distance in meters to the yellow flag incident ahead, or white flag (slow car) ahead? (Have seen this used in other programs so it appears that ACC outputs this data)

2) Drive-through or stop-and-go penalties (with associated time penalty in seconds) per driver

3) Mandatory pit requirement & completion per driver (i.e. DataCorePlugin.GameRawData.Graphics.missingMandatoryPits & DataCorePlugin.GameRawData.Graphics.MandatoryPitDone)

**Comment by kaiusl** [comment]
Hi, thanks for the suggestions.

1. It's not directly available from ACC. Others must be calculating it manually but I think it doesn't quite fit within a leaderboard plugin.
2. These are available, sort of...,  there were some issues with them. So I didn't add them. I may take another look.
3. Again these are not directly available for all the cars but probably we could calculate them. However I already see some probably issues with it. 

I'll add 2 and 3 to the todo list.

**Comment by kaiusl** [comment]
> I also forgot to mention regarding sector time data, is it possible to have the last recorded sector per car (i.e. so for example, if currently in S3 we can obtain the current lap S1 and S2).? This would allow for a head to head comparison and gap evolution between cars.

Unfortunately the sector times of current lap are always sent to us as nulls.

> Regarding 3., I assume ACC also does not output the pitstop rules like mandatory tyre change, refuel, etc.?

Only thing we get directly from ACC is if the car is in the pit lane. For player car there is more information but for everyone else the data is quite limited. At first I thought we could maybe figure out some other way what the car actually did in the pits but it gets more trickier and error prone the more I think about it.

**Comment by Mtrade** [comment]
> > I also forgot to mention regarding sector time data, is it possible to have the last recorded sector per car (i.e. so for example, if currently in S3 we can obtain the current lap S1 and S2).? This would allow for a head to head comparison and gap evolution between cars.
> 
> Unfortunately the sector times of current lap are always sent to us as nulls.
> 
> > Regarding 3., I assume ACC also does not output the pitstop rules like mandatory tyre change, refuel, etc.?
> 
> Only thing we get directly from ACC is if the car is in the pit lane. For player car there is more information but for everyone else the data is quite limited. At first I thought we could maybe figure out some other way what the car actually did in the pits but it gets more trickier and error prone the more I think about it.

Ok understood, appreciate you looking into it either way. 
I suppose a broadcast client like ACC director for example (https://www.assettocorsa.net/forum/index.php?threads/accdirector-v1-0-4-broadcast-client.57202/) also wouldn't have access to additional data like which cars on the entire grid have made their mandatory pit stop, live sector times, etc,.?

**Comment by kaiusl** [comment]
That's right. All such applications have access to the same base data.

**Comment by Mtrade** [comment]
Hi,
Wondering if you were able to make any progress on any of these? Also, hopefully you can update the laps_data folder for Valencia or any other new tracks?

Thanks!

**Comment by kaiusl** [comment]
No progress on the enhancements yet.

> Also, hopefully you can update the laps_data folder for Valencia or any other new tracks?

I haven't played ACC in a while and most likely won't buy the DLC (at least not right away). So unfortunately cannot add the laps_data for new tracks.
However I have a small utility plugin for SimHub that collects that data. I should upload it and then you could collect the needed data and we can update it.

**Comment by Mtrade** [comment]
> No progress on the enhancements yet.
> 
> > Also, hopefully you can update the laps_data folder for Valencia or any other new tracks?
> 
> I haven't played ACC in a while and most likely won't buy the DLC (at least not right away). So unfortunately cannot add the laps_data for new tracks. However I have a small utility plugin for SimHub that collects that data. I should upload it and then you could collect the needed data and we can update it.

Sure, happy to assist with anything that's needed.
