### ISSUE TITLE
Generate lap data for Valencia

### ISSUE THREAD

**Issue by kaiusl** [kaiusl/KLPlugins.DynLeaderboards#16]
As I won't be getting the new ACC DLC on the 19th and thus cannot generate the lap data for Valencia, I need some help updating the plugin.
@Mtrade You still up for helping?

# How to

* Download and install utility plugin for SimHub from https://github.com/kaiusl/KLPlugins.DataExport/releases/tag/0.0.1
* Run two 10min AI qualy sessions (see below for the images with session settings):
    * one with GT3, CUP21, ST21, CHL
    * another for GT4, TCX
  (so they don't trip each other up that much, also don't max out the opponents for the same reason)
  This will track the AI cars and save their best lap data.
* Upload the generated files from `\SimHub\PluginsData\KLPlugins\DataExport\laps_data\raw`.

![1](https://user-images.githubusercontent.com/37976028/232774912-c2bcb556-003a-4a46-910c-7f6a9ea359c0.png)
![4](https://user-images.githubusercontent.com/37976028/232774923-d1c3f274-abfc-4f25-8962-62edf2057476.png)

**Comment by Mtrade** [comment]
Sure, will get on it as soon as I'm able. Any particular ratio of cars needed for GT3 vs cup/ST/CHL in the session?

**Comment by kaiusl** [comment]
I used 4 of each, shouldn't really matter as long as there are at least few cars from each class.

**Comment by kaiusl** [comment]
I'm not quite sure what you mean... I think simplest way to do it is if you just .zip them up and add them to a comment here, you should be able to add files to a comment?

**Comment by kaiusl** [comment]
New lap data added. Thank you very much @Mtrade. New release will be up shortly.
