### ISSUE TITLE
Best Lap Sectors = Last Lap Sectors, and Position Overall Start = -1 for all cars on race restart

### ISSUE THREAD

**Issue by MrAgentSmith** [kaiusl/KLPlugins.DynLeaderboards#23]
### Describe the bug

Hi,

The best lap sectors are equal to the last lap sectors, even when the lap is not your best lap, i.e. .Laps.Best.S1 = .Laps.Last.S1 (and the same for S2 and S3).

Also if you restart a race, then the Position.Overall.Start = -1 for all cars.

Otherwise a great plugin.

### Reproduction steps

I am running the latest version of ACC (v 1.9.5) and the latest version of Simhub (v 9.15), do your fastest lap and then do a slow lap.  At which point .Laps.Best.S1 = .Laps.Last.S1 instead of .Laps.Best.S1 still relating to your best lap.

After doing them lap, restart the race and then Position.Overall.Start = -1 for all cars instead of their correct starting position.

### Plugin version

1.3.2

### SimHub version

9.15

**Comment by kaiusl** [comment]
Thank you for the report.

Fixed in 7901ed51cd9d6a4e57bb5818678197ac0cce2bae, 362327c4927dc58b5fa0dbc0b98860b035d063ec and released in [v1.3.3](https://github.com/kaiusl/KLPlugins.DynLeaderboards/releases/tag/v1.3.3) 🎉
