### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by mugen5** [kaiusl/KLPlugins.DynLeaderboards#30]
### Describe the bug

I followed every instruction to get this to work but have been unsuccessful. ACC and SimHub are up to date. Downloaded the files from Github and copy pasted the files inside SimHub folder to SimHub Root folder. Imported the dashboard. Background is green in general setting. I tried with both a SImhub replay(from ACC) and while in game and on track. When I launch the dashboard it's all blank. When checking available properties in SimHub all the properties associated with this plugin shows value of [null]. It seems that it's not seeing any data. I tried on 2 separate PC with same results. The log file is attached. 
[SimHub.1.zip](https://github.com/user-attachments/files/16900105/SimHub.1.zip)

### Plugin version

1.4.5

### SimHub version

9.4.4

**Comment by kaiusl** [comment]
First, this plugin doesn't work with SimHub replays at all (at least v1.x, it will change in v2.x once it's ready). It needs a live ACC connection as we connect to ACC directly ourselves.

About the issue, it seems like there is some file missing but the errors don't look like from this plugin. I suspect they may be from somewhere else. I tried deleting all the relevant files for this plugin but couldn't reproduce the issue.

Could you try:
1. Disable all other third-party plugins and see if that changes anything.
2. Try running without the dashboard, just check the properties.
3. Try to clean install SimHub, it has fixed quite a few issues for other people before.

If those doesn't change anything could you send the logs from running without other plugins and without dashboard open. Also send all the files from SimHub/logs. The most recent log file is SimHub.txt but longer logs will be split into multiple files.

**Comment by mugen5** [comment]
Hi
Thanks for the quick reply. I thought for sure I tried it with ACC running but mostly tested with SimHub replay. I just tried again with ACC running and it seems to work. Although I did re download all the files before posting and copied the files to SimHub folder. So either I did have some files missing  or perhaps it was another dashboard I was testing with ACC on. In either case it works now so thanks for your help and this great plugin. I didn't see any mention that it doesn't work with replays so maybe something you want to add to the notes. Also I see you posted on GitHub you need data for Red Bull Ring. Do you still need this? If so I could probably do it early next week. And just to be clear when running the qualy sessions can I just leave AI running alone or do I have to be on track as well? Or does it make a difference. 
    On Friday, September 6, 2024 at 03:16:33 a.m. ADT, Kaius Loos ***@***.***> wrote:  
 
 


First, this plugin doesn't work with SimHub replays at all (at least v1.x, it will change in v2.x once it's ready). It needs a live ACC connection as we connect to ACC directly ourselves.

About the issue, it seems like there is some file missing but the errors don't look like from this plugin. I suspect they may be from somewhere else. I tried deleting all the relevant files for this plugin but couldn't reproduce the issue.

Could you try:
   
   - Disable all other third-party plugins and see if that changes anything.
   - Try running without the dashboard, just check the properties.
   - Try to clean install SimHub, it has fixed quite a few issues for other people before.

If those doesn't change anything could you send the logs from running without other plugins and without dashboard open. Also send all the files from SimHub/logs. The most recent log file is SimHub.txt but longer logs will be split into multiple files.

**Comment by kaiusl** [comment]
I'm glad it started to work :)

> I didn't see any mention that it doesn't work with replays so maybe something you want to add to the notes.

I'll do it for next release.

> Also I see you posted on GitHub you need data for Red Bull Ring. Do you still need this? If so I could probably do it early next week. And just to be clear when running the qualy sessions can I just leave AI running alone or do I have to be on track as well? Or does it make a difference.

No need, those files won't be needed in the next release anymore. Or more precisely they will be generated automatically. I should really close that issue.

However if you meanwhile do want better gaps calculation on RBR you can generate those files for yourself (or I can do that if you post the raw files generated here). But I don't plan to make any more releases before next big update where those files won't be needed anymore.
