### ISSUE TITLE
Leaderboard rotation resets to default

### ISSUE THREAD

**Issue by serek4** [kaiusl/KLPlugins.DynLeaderboards#5]
dynamic leaderboards -> leaderboard rotation resets to default on simhub restart (all enabled and in default order)

**Comment by kaiusl** [comment]
Turns out that the leaderboard rotation was not saved and thus kept reseting to the default. Fixed in 80e8953aecb3569bef49557b48932322fc6bda1f . 

I found some other issues with settings, will fix them too and post a small patch tomorrow.

**Comment by kaiusl** [comment]
Released in [1.1.1](https://github.com/kaiusl/KLPlugins.DynLeaderboards/releases/tag/v1.1.1).
